### PR TITLE
Add a basic search page

### PR DESCRIPTION
**Pull request by sorawee**
This commit hacks the glossary page to be a search result page in the same time.
Note that Scribble has a functionality to propagate query strings via links,
but this would interact badly with this new feature, so we need to explicitly
patch it.

### CODE REVIEW

**Comment by sorawee** [comment]
Screenshot:

2018-08-02-063714_1033x893_scrot

**Comment by blerner** [comment]
I'd tweak this slightly to add:

```
Showing results only for: "app"
[x] Clear search filter
```

and clicking the "Clear" link would take you to the Glossary page, without any query terms...

**Comment by sorawee** [comment]
peek 2018-08-02 17-26

@blerner @shriram is this OK?

Some frames in the beginning of the GIF do not appear, but there's nothing interesting there (just to show that the search box will link to the glossary page)

**Comment by sorawee** [comment]
Screetshot (just in case you can't view the GIF)

2018-08-02-174414_996x920_scrot

**Comment by shriram** [comment]
Yes, wow!

**Pull request merged**
